Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "C:\Users\DarrellG\Documents\Programming\birdquiz2.1 - Merge\app\__init__.py", line 13, in <module>
    from flask_sqlalchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_sqlalchemy'
Traceback (most recent call last):
  File "C:\Users\DarrellG\Documents\Programming\birdquiz2.1 - Merge\birdquiz.py", line 7, in <module>
    from app import app
  File "C:\Users\DarrellG\Documents\Programming\birdquiz2.1 - Merge\app\__init__.py", line 12, in <module>
    from flask import Flask
ImportError: No module named flask
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "C:\Users\DarrellG\Documents\Programming\birdquiz2.1 - Merge\app\__init__.py", line 13, in <module>
    from flask_sqlalchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_sqlalchemy'
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "C:\Users\DarrellG\Documents\Programming\birdquiz2.1 - Merge\app\__init__.py", line 13, in <module>
    from flask_sqlalchemy import SQLAlchemy
ModuleNotFoundError: No module named 'flask_sqlalchemy'
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "C:\Users\DarrellG\Documents\Programming\birdquiz2.1 - Merge\app\__init__.py", line 13, in <module>
    from Flask_SQLAlchemy import SQLAlchemy
ModuleNotFoundError: No module named 'Flask_SQLAlchemy'
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "C:\Users\DarrellG\Documents\Programming\birdquiz2.1 - Merge\app\__init__.py", line 13, in <module>
    from Flask_SQLAlchemy import SQLAlchemy
ModuleNotFoundError: No module named 'Flask_SQLAlchemy'
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    from app import app
  File "C:\Users\DarrellG\Documents\Programming\birdquiz2.1 - Merge\app\__init__.py", line 21, in <module>
    from app import views, models
  File "C:\Users\DarrellG\Documents\Programming\birdquiz2.1 - Merge\app\views.py", line 6, in <module>
    from .forms import GuessForm, HomePageForm, BlankForm
  File "C:\Users\DarrellG\Documents\Programming\birdquiz2.1 - Merge\app\forms.py", line 3, in <module>
    from flask_wtf import FlaskForm as Form
ModuleNotFoundError: No module named 'flask_wtf'
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 225-629-428
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:34:57] "[32mGET / HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:34:57] "[37mGET /setup HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:34:57] "[37mGET /static/style.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:34:57] "[37mGET /static/map.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:34:57] "[37mGET /static/pretty-checkbox.css HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:34:57] "[37mGET /static/repeating_birds.jpg HTTP/1.1[0m" 200 -
INFO:root:The file Thumbs.db does not have the right file extension. Accepted extensions are: ['.ppm', '.jpg', '.jpeg', '.png'].
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:05] "[32mPOST /setup HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:05] "[37mGET /question?quizID=576 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:05] "[37mGET /static/photos/Tom_Grey/SnowGoose6_padded.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:10] "[32mPOST /question?quizID=576 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:10] "[37mGET /answer?quizID=576 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:12] "[32mPOST /answer?quizID=576 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:12] "[37mGET /question?quizID=576 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:12] "[37mGET /static/photos/Tom_Grey/MewGull25_padded.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:16] "[32mPOST /question?quizID=576 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:16] "[37mGET /answer?quizID=576 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:17] "[32mPOST /answer?quizID=576 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:18] "[32mGET /question?quizID=576 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:18] "[37mGET /finsh?quizID=576 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:18] "[37mGET /static/photos/Tom_Grey/RidgwaysRail8_padded.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:22] "[32mPOST /finsh?quizID=576 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:22] "[37mGET /setup?quizID=576 HTTP/1.1[0m" 200 -
INFO:root:The file Thumbs.db does not have the right file extension. Accepted extensions are: ['.ppm', '.jpg', '.jpeg', '.png'].
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:27] "[32mPOST /setup?quizID=576 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:27] "[37mGET /question?quizID=577 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:27] "[37mGET /static/photos/Tom_Grey/GreatBlueHerons7_padded.png HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:31] "[32mPOST /question?quizID=577 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:31] "[37mGET /answer?quizID=577 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:33] "[32mPOST /answer?quizID=577 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:33] "[37mGET /question?quizID=577 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:33] "[37mGET /static/photos/Darrell_Good/BRTHdg1.jpg HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:38] "[32mPOST /question?quizID=577 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:38] "[37mGET /answer?quizID=577 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:40] "[32mPOST /answer?quizID=577 HTTP/1.1[0m" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:40] "[37mGET /question?quizID=577 HTTP/1.1[0m" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Jan/2021 14:35:40] "[37mGET /static/photos/Darrell_Good/WEGUdg1.JPG HTTP/1.1[0m" 200 -
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 225-629-428
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
Traceback (most recent call last):
  File "C:\Users\DarrellG\Documents\Programming\birdquiz2.1 - Merge\config.py", line 13, in <module>
    from app import DataHandler as DH
  File "C:\Users\DarrellG\Documents\Programming\birdquiz2.1 - Merge\app\__init__.py", line 12, in <module>
    from flask import Flask
ImportError: No module named flask
INFO:werkzeug: * Detected change in 'C:\\Users\\DarrellG\\Documents\\Programming\\birdquiz2.1 - Merge\\run.py', reloading
INFO:werkzeug: * Restarting with stat
WARNING:werkzeug: * Debugger is active!
INFO:werkzeug: * Debugger PIN: 225-629-428
INFO:werkzeug: * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
